# Generated by Django 4.1.7 on 2023-05-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("Client", "Client"), ("Manager", "Manager")],
                default="Client",
                max_length=20,
                null=True,
            ),
        ),
    ]
