# Generated by Django 4.1.7 on 2023-05-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client",
            new_name="BankClient",
        ),
    ]
