# Generated by Django 4.1.7 on 2023-05-24 08:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("loan_amount", models.FloatField(default=0, max_length=255)),
                ("interest_rate", models.FloatField(max_length=255)),
                ("reduction_rate", models.FloatField(max_length=255)),
                ("loan_start_date", models.DateField(default=datetime.datetime.now)),
                ("loan_end_date", models.DateField()),
                ("paid_amount", models.FloatField(default=0)),
                (
                    "rest_to_pay",
                    models.FloatField(default=0, max_length=255, null=True),
                ),
                (
                    "monthly_withdrawn_amount",
                    models.FloatField(blank=True, default=0, max_length=255, null=True),
                ),
                (
                    "contract_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("repayment_method", models.CharField(max_length=50)),
                (
                    "loan_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Success", "Success"),
                            ("Confirmed", "Confirmed"),
                            ("Refused", "Refused"),
                        ],
                        default="Pending",
                        max_length=32,
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.bank",
                    ),
                ),
            ],
        ),
    ]
