# Generated by Django 4.1.7 on 2023-05-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="reduction_rate",
            field=models.FloatField(default=0, max_length=255),
        ),
    ]
