# Generated by Django 4.1.7 on 2023-05-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='admin',
        ),
    ]
